#!/bin/bash

OLD_HOME=$HOME
cd $OPENSHIFT_REPO_DIR
export HOME=$OPENSHIFT_REPO_DIR

$OPENSHIFT_REPO_DIR/node_modules/grunt_cli/bin/grunt build --gruntfile $OPENSHIFT_REPO_DIR/public/project/Gruntfile.js

export HOME=$OLD_HOME
